let s:is_windows = has('win32') || has('win64')

function! IsWindows() abort
  return s:is_windows
endfunction
if &compatible
  set nocompatible
endif
let s:rc_dir = expand('<sfile>:p:h')
let s:dein_dir = expand('~/.vim')
let s:dein_repo_dir = s:dein_dir.'/repos/github.com/Shougo/dein.vim'

execute 'set runtimepath+='.s:dein_repo_dir

if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    call dein#add(fnamemodify(s:dein_repo_dir,':p'))
    let g:rc_dir = fnamemodify(expand('<sfile>'),':h')
    let s:toml = g:rc_dir.'/dein.toml'
    let s:lazy_toml = g:rc_dir.'/dein_lazy.toml'
    let s:nvim_toml = g:rc_dir.'/deineo.toml'
    let s:vim_toml = g:rc_dir.'/deinvim.toml'

    call dein#load_toml(s:toml,{'lazy':0})
    call dein#load_toml(s:lazy_toml,{'lazy':1})
    if has('nvim')
        call dein#load_toml(s:nvim_toml, {'lazy':1})
    endif
    if has('vim')
        call dein#load_toml(s:vim_toml {'lazy':1})
    endif
    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
	call dein#install()
endif


function! s:source_rc(path) abort
	let abspath = s:rc_dir.'/'.a:path
	execute 'source '.abspath
endfunction

call s:source_rc('my.vim')
call s:source_rc('template.vim')
call s:source_rc('color-scheme.vim')

call dein#call_hook('source')
call dein#call_hook('post_source')

syntax enable
filetype plugin indent on
set runtimepath^=~/.vim,
